DEFAULT_MIN_VALUE = -90000
DEFAULT_MAX_VALUE = 90000
DEFAULT_MASS = 65
DEFAULT_FADE_SCREEN_DURATION = 10
DEFAULT_SHOW_USER_DURATION = 15000
DEFAULT_MinSpeed = 5
DEFAULT_MaxSpeed = 15
DEFAULT_MinTime = 1
DEFAULT_MaxTime = 7
DEFAULT_BlockMinTime = 1
DEFAULT_BlockMaxTime = 20
DEFAULT_DriveDirMinTime = 1
DEFAULT_DriveDirMaxTime = 7
DEFAULT_cameraFun_ZoomMax = 500
DEFAULT_cameraFun_ZoomMin = 0
DEFAULT_cameraFun_UseZoom = "True"
DEFAULT_cameraFun_TimeMin = 1
DEFAULT_cameraFun_TimeMax = 5
DEFAULT_LAUNCHVEHUPIMP = "35"
DEFAULT_LAUNCHVEHFWDIMP = "10"
DEFAULT_INTERIORCAMMINTIME = 3
DEFAULT_INTERIORCAMMAXTIME = 5
DEFAULT_TOGWIPERMINTIME = 2
DEFAULT_TOGWIPERMAXTIME = 5

DEFAULT_FADE_SCREEN_WARNING_MESSAGE = "@FADE_SCREEN_WARNING"

DEFAULT_SHOW_USER_WARNING_MESSAGE  = "@SHOWUSER_MSG1"
DEFAULT_SHOW_USER_WARNING_MESSAGE2 = "@SHOWUSER_MSG2"
DEFAULT_SHOW_USER_WARNING_MESSAGE3 = "@SHOWUSER_MSG3"
DEFAULT_SHOW_USER_WARNING_MESSAGE4 = "@SHOWUSER_MSG4"
DEFAULT_SHOW_USER_WARNING_MESSAGE5 = "@SHOWUSER_MSG5"
DEFAULT_SHOW_HI_WARNING_MESSAGE    = "@SHOWHI_MSG"

DEFAULT_CLEAR_FUEL_MESSAGE            = "@CLEAR_FUEL_MESSAGE"
DEFAULT_SET_BROKEN_MESSAGE            = "@SET_BROKEN_MESSAGE"
DEFAULT_ADJUST_MONEY_POSITIVE_MESSAGE = "@ADJUST_MONEY_POSITIVE"
DEFAULT_ADJUST_MONEY_NEGATIVE_MESSAGE = "@ADJUST_MONEY_NEGATIVE"
DEFAULT_SET_DIRT_MESSAGE              = "@SET_DIRT_MESSAGE"
DEFAULT_SET_DIRT_CLEANMESSAGE         = "@SET_DIRT_CLEANMESSAGE"
DEFAULT_TEMPORARY_MASS_MESSAGE        = "@TEMPORARY_MASS_MESSAGE"
DEFAULT_SETTIME_MESSAGE               = "@SETTIME_MESSAGE"

DEFAULT_WARNING_SPEED_LIMIT_MESSAGE   = "@SPEED_WARNING_LIMIT"
DEFAULT_WARNING_MOTOR_PAUSE_MESSAGE   = "@SPEED_WARNING_PAUSE"
DEFAULT_WARNING_MOTOR_OVERSPEED_MESSAGE = "@SPEED_WARNING_OVERSPEED"
DEFAULT_WARNING_MOTOR_BLOCKED_MESSAGE  = "@SPEED_WARNING_BLOCKED"
DEFAULT_WARNING_MOTOR_STOPPED_MESSAGE  = "@BLOCKENGINE_STOPPED"
DEFAULT_WARNING_MOTOR_ACTIVE_MESSAGE   = "@BLOCKENGINE_ACTIVE"
DEFAULT_WARNING_MOTOR_IGNORED_MESSAGE  = "@BLOCKENGINE_IGNORED"
DEFAULT_WARNING_MOTOR_FAIL_MESSAGE     = "@BLOCKENGINE_FAIL"

DEFAULT_BlockTabMessage        = "@BLOCK_TAB_MESSAGE"
DEFAULT_BlockTabUnblockMessage = "@BLOCK_TAB_UNBLOCK"
DEFAULT_TryTabMessage          = "@BLOCK_TAB_TRY"

DEFAULT_DriveDirWarnmessage = "@DRIVEDIR_WARN"
DEFAULT_DriveDirResetmessage = "@DRIVEDIR_RESET"
DEFAULT_DriveDirBlockWarn   = "@DRIVEDIR_BLOCKWARN"
DEFAULT_DriveDirForward     = "@DRIVEDIR_FORWARD"
DEFAULT_DriveDirBackward    = "@DRIVEDIR_BACKWARD"

DEFAULT_cameraFun_WarnMessage     = "@CAMERA_WARN"
DEFAULT_cameraFun_cameraBlocked   = "@CAMERA_BLOCKED"
DEFAULT_cameraFun_cameraUnblocked = "@CAMERA_UNBLOCKED"

DEFAULT_Adjust_FUEL_GETMESSAGE = "@ADJUST_FUEL_GET"
DEFAULT_Adjust_FUEL_REMMESSAGE = "@ADJUST_FUEL_REM"

DEFAULT_BlockAndLock_KEYOUT   = "@BLOCKANDLOCK_KEYOUT"
DEFAULT_BlockAndLock_KEYFOUND = "@BLOCKANDLOCK_KEYFOUND"

DEFAULT_triggerHonk_warnmessage = "@TRIGGERHONK_WARN"

DEFAULT_forbiddenSteeringDirLeft         = "@FORBIDDIR_LEFT"
DEFAULT_forbiddenSteeringDirRight        = "@FORBIDDIR_RIGHT"
DEFAULT_forbiddenSteeringDirBlockWarn    = "@FORBIDDIR_BLOCKWARN"
DEFAULT_forbiddenSteeringDirBlockWarnTry = "@FORBIDDIR_BLOCKWARNTRY"
DEFAULT_forbiddenSteeringDirBlockWarnReset = "@FORBIDDIR_BLOCKWARNRESET"

DEFAULT_invertControlsWarnMessage    = "@INVERT_WARN"
DEFAULT_invertControlsBlockMessage   = "@INVERT_BLOCK"
DEFAULT_invertControlsUnblockMessage = "@INVERT_UNBLOCK"

DEFAULT_RANDOMSTEER_BLOCKSTART   = "@RANDOMSTEER_BLOCKSTART"
DEFAULT_RANDOMSTEER_SEGMENTSTART = "@RANDOMSTEER_SEGMENTSTART"
DEFAULT_RANDOMSTEER_BLOCKEND     = "@RANDOMSTEER_BLOCKEND"
DEFAULT_RANDOMSTEER_DIRLEFT      = "@RANDOMSTEER_DIRLEFT"
DEFAULT_RANDOMSTEER_DIRRIGHT     = "@RANDOMSTEER_DIRRIGHT"

DEFAULT_LAUNCHVEHWARNMESSAGE = "@LAUNCHVEH_WARN"

DEFAULT_INTERIORCAMWARNMESSAGE   = "@INTERIORCAM_WARN"
DEFAULT_INTERIORCAMBLOCKMESSAGE  = "@INTERIORCAM_BLOCK"
DEFAULT_INTERIORCAMUNBLOCKMESSAGE = "@INTERIORCAM_UNBLOCK"

DEFAULT_TOGWIPERMESSAGE            = "@TOGWIPER_WARN"
DEFAULT_TOGWIPERDEAKTIVATEMESSAGE  = "@TOGWIPER_DEACT"

-- WalkingEvent
DEFAULT_WALKING_START        = "@WALKING_START"
DEFAULT_WALKING_ENTERBLOCKED = "@WALKING_ENTERBLOCKED"
DEFAULT_WALKING_DONE         = "@WALKING_DONE"
DEFAULT_WALKING_WARN1        = "@WALKING_WARN1"
DEFAULT_WALKING_WARN2        = "@WALKING_WARN2"
DEFAULT_WALKING_WARN3        = "@WALKING_WARN3"
DEFAULT_WALKING_WARN4        = "@WALKING_WARN4"
DEFAULT_WALKING_WARN5        = "@WALKING_WARN5"

-- IdleChaos Defaults
DEFAULT_IDLECHAOS_MIN_SPEED_KPH = 1         
DEFAULT_IDLECHAOS_STAND_MS      = 1200       
DEFAULT_IDLECHAOS_EFF_MIN_MS    = 3000
DEFAULT_IDLECHAOS_EFF_MAX_MS    = 8000
DEFAULT_IDLECHAOS_COOLDOWN_MS   = 1000

DEFAULT_IDLECHAOS_START   = "@IDLECHAOS_START"   
DEFAULT_IDLECHAOS_TICK    = "@IDLECHAOS_TICK"     
DEFAULT_IDLECHAOS_EFFECT  = "@IDLECHAOS_EFFECT"  
DEFAULT_IDLECHAOS_END     = "@IDLECHAOS_END"
DEFAULT_IDLECHAOS_MESSAGE_MODE = "default"


DEFAULT_FLAT_TIRE_MIN_MINUTES = 1
DEFAULT_FLAT_TIRE_MAX_MINUTES = 3
DEFAULT_TIRE_PARTY_MIN_MINUTES = 1
DEFAULT_TIRE_PARTY_MAX_MINUTES = 2
DEFAULT_TIRE_PARTY_MIN_SWITCH_MS = 1200
DEFAULT_TIRE_PARTY_MAX_SWITCH_MS = 3000

DEFAULT_FLAT_TIRE_START = "@FLAT_TIRE_START"
DEFAULT_FLAT_TIRE_TICK = "@FLAT_TIRE_TICK"
DEFAULT_FLAT_TIRE_DONE = "@FLAT_TIRE_DONE"
DEFAULT_FLAT_TIRE_NOSUPPORT = "@FLAT_TIRE_NOSUPPORT"
DEFAULT_FLAT_TIRE_PULLLEFT = "@FLAT_TIRE_PULLLEFT"
DEFAULT_FLAT_TIRE_PULLRIGHT = "@FLAT_TIRE_PULLRIGHT"

DEFAULT_TIRE_PARTY_START = "@TIRE_PARTY_START"
DEFAULT_TIRE_PARTY_FLAT = "@TIRE_PARTY_FLAT"
DEFAULT_TIRE_PARTY_FULL = "@TIRE_PARTY_FULL"
DEFAULT_TIRE_PARTY_DONE = "@TIRE_PARTY_DONE"
DEFAULT_TIRE_PARTY_NOSUPPORT = "@TIRE_PARTY_NOSUPPORT"

DEFAULT_FLAT_TIRE_BRAKE_PULSE_MS = 900
DEFAULT_FLAT_TIRE_WOBBLE_MS = 260
DEFAULT_FLAT_TIRE_PULL_STRENGTH_MIN = 0.20
DEFAULT_FLAT_TIRE_PULL_STRENGTH_MAX = 0.30
DEFAULT_FLAT_TIRE_WOBBLE_STRENGTH_MIN = 0.05
DEFAULT_FLAT_TIRE_WOBBLE_STRENGTH_MAX = 0.10
DEFAULT_FLAT_TIRE_FORWARD_CLAMP_MIN = 0.55
DEFAULT_FLAT_TIRE_FORWARD_CLAMP_MAX = 0.67
DEFAULT_FLAT_TIRE_TICK_INTERVAL_MS = 4500
DEFAULT_FLAT_TIRE_MESSAGE_MODE = "default"

DEFAULT_TIRE_PARTY_FLAT_MESSAGE_MS = 700
DEFAULT_TIRE_PARTY_FULL_MESSAGE_MS = 500
DEFAULT_TIRE_PARTY_MESSAGE_MODE = "default"


DEFAULT_TAB_TRAP_MIN_LOCK_MINUTES = 1
DEFAULT_TAB_TRAP_MAX_LOCK_MINUTES = 5
DEFAULT_TAB_TRAP_MIN_SWITCH_COUNT = 3
DEFAULT_TAB_TRAP_MAX_SWITCH_COUNT = 8
DEFAULT_TAB_TRAP_MIN_SWITCH_DELAY_MS = 350
DEFAULT_TAB_TRAP_MAX_SWITCH_DELAY_MS = 1100

DEFAULT_TAB_TRAP_START = "@TAB_TRAP_START"
DEFAULT_TAB_TRAP_SWITCH = "@TAB_TRAP_SWITCH"
DEFAULT_TAB_TRAP_LOCKED = "@TAB_TRAP_LOCKED"
DEFAULT_TAB_TRAP_TRY_EXIT = "@TAB_TRAP_TRY_EXIT"
DEFAULT_TAB_TRAP_TRY_SWITCH = "@TAB_TRAP_TRY_SWITCH"
DEFAULT_TAB_TRAP_DONE = "@TAB_TRAP_DONE"
DEFAULT_TAB_TRAP_TOO_FEW = "@TAB_TRAP_TOO_FEW"


DEFAULT_SHOW_USER_MESSAGE_MODE = "default"
DEFAULT_SHOW_HI_DURATION = 10000
DEFAULT_SHOW_HI_MESSAGE_MODE = "default"
DEFAULT_SHOW_SIMU_DURATION = 15000
DEFAULT_SHOW_SIMU_MESSAGE_MODE = "default"

DEFAULT_MESSAGE_API_MODE = "twitch"
DEFAULT_MESSAGE_API_BACKGROUND = "true"
DEFAULT_MESSAGE_API_TOAST_X = 0.5
DEFAULT_MESSAGE_API_TOAST_Y = 0.92
DEFAULT_MESSAGE_API_TOAST_SCALE = 0.022
DEFAULT_MESSAGE_API_TOAST_ALIGN = "center"
DEFAULT_MESSAGE_API_CENTER_X = 0.5
DEFAULT_MESSAGE_API_CENTER_Y = 0.46
DEFAULT_MESSAGE_API_CENTER_SCALE = 0.03
DEFAULT_MESSAGE_API_CENTER_ALIGN = "center"
DEFAULT_MESSAGE_API_PADDING_X = 0.008
DEFAULT_MESSAGE_API_PADDING_Y = 0.006
DEFAULT_MESSAGE_API_BG_R = 0
DEFAULT_MESSAGE_API_BG_G = 0
DEFAULT_MESSAGE_API_BG_B = 0
DEFAULT_MESSAGE_API_BG_A = 0.65
DEFAULT_MESSAGE_API_TEXT_R = 1
DEFAULT_MESSAGE_API_TEXT_G = 1
DEFAULT_MESSAGE_API_TEXT_B = 1
DEFAULT_MESSAGE_API_TEXT_A = 1
DEFAULT_MESSAGE_API_CONSOLE_PREFIX = "[FarmingLive]"

DEFAULT_DRIVE_THAT_MIN_LOCK_MINUTES = 1
DEFAULT_DRIVE_THAT_MAX_LOCK_MINUTES = 4
DEFAULT_DRIVE_THAT_START = "@DRIVE_THAT_START"
DEFAULT_DRIVE_THAT_LOCKED = "@DRIVE_THAT_LOCKED"
DEFAULT_DRIVE_THAT_TRY_EXIT = "@DRIVE_THAT_TRY_EXIT"
DEFAULT_DRIVE_THAT_TRY_SWITCH = "@DRIVE_THAT_TRY_SWITCH"
DEFAULT_DRIVE_THAT_DONE = "@DRIVE_THAT_DONE"
DEFAULT_DRIVE_THAT_FAILED = "@DRIVE_THAT_FAILED"
DEFAULT_DRIVE_THAT_TOO_FEW = "@DRIVE_THAT_TOO_FEW"
DEFAULT_DRIVE_THAT_ENTER_TIMEOUT_MS = 2500
DEFAULT_DRIVE_THAT_ENTER_RETRY_MS = 500
DEFAULT_DRIVE_THAT_RECOVERY_RETRY_MS = 1000
DEFAULT_DRIVE_THAT_MESSAGE_MODE = "default"


DEFAULT_MATHGAME_MIN_QUESTIONS = 3
DEFAULT_MATHGAME_MAX_QUESTIONS = 6
DEFAULT_MATHGAME_MIN_PENALTY_MINUTES = 1
DEFAULT_MATHGAME_MAX_PENALTY_MINUTES = 2
DEFAULT_MATHGAME_QUESTION_TIMEOUT_MS = 9000
DEFAULT_MATHGAME_BETWEEN_QUESTION_MS = 900
DEFAULT_MATHGAME_ANSWER_THRESHOLD = 0.45
DEFAULT_MATHGAME_NEUTRAL_THRESHOLD = 0.12
DEFAULT_MATHGAME_RECENTER_MS = 350
DEFAULT_MATHGAME_START_DELAY_MS = 850
DEFAULT_MATHGAME_MESSAGE_MODE = "default"

DEFAULT_MATHGAME_START = "@MATHGAME_START"
DEFAULT_MATHGAME_QUESTION = "@MATHGAME_QUESTION"
DEFAULT_MATHGAME_CORRECT = "@MATHGAME_CORRECT"
DEFAULT_MATHGAME_WRONG = "@MATHGAME_WRONG"
DEFAULT_MATHGAME_TIMEOUT = "@MATHGAME_TIMEOUT"
DEFAULT_MATHGAME_RESULT_NOPENALTY = "@MATHGAME_RESULT_NOPENALTY"
DEFAULT_MATHGAME_RESULT_PENALTY = "@MATHGAME_RESULT_PENALTY"
DEFAULT_MATHGAME_PENALTY_START = "@MATHGAME_PENALTY_START"
DEFAULT_MATHGAME_PENALTY_TICK = "@MATHGAME_PENALTY_TICK"
DEFAULT_MATHGAME_PENALTY_DONE = "@MATHGAME_PENALTY_DONE"
